// LEGACY – non utilisé dans la version actuelle du site. À supprimer après vérification.
/**
 * Collection de projets EfSVP (CMS-ready)
 * Décrit chaque histoire avec un modèle extensible
 */

/**
 * @typedef {"delivered" | "in_production"} ProjectStatus
 *
 * @typedef {Object} Project
 * @property {string} slug Identifiant unique du projet
 * @property {string} title Titre court du projet
 * @property {string} client Commanditaire principal
 * @property {string[]} [coClients] Partenaires institutionnels associés
 * @property {number} year Année principale du projet
 * @property {string} [period] Période multi-année si applicable
 * @property {string} sector Secteur d'activité
 * @property {string} format Format narratif ou musical
 * @property {string} typology Typologie du client
 * @property {string} location Territoire principal
 * @property {string} tagline Phrase d'accroche courte
 * @property {string} shortDescription Résumé de 2 à 3 phrases
 * @property {string} longDescription Version longue pour fiche détaillée
 * @property {string[]} roles Rôles assurés par EfSVP
 * @property {string[]} [partners] Partenaires artistiques ou techniques
 * @property {string[]} themes Thématiques principales
 * @property {string[]} [devices] Dispositifs narratifs ou musicaux
 * @property {ProjectStatus} status Statut du projet
 * @property {number} [playsCount] Nombre de représentations lorsque pertinent
 * @property {boolean} [isFeatured] Marquage de mise en avant
 * @property {number} order Ordre d'affichage dans la section
 */

/** @type {Project[]} */
export const projectsCollection = [
  {
    slug: 'sival-bruno-dupont',
    title: 'Destination Angers — Saga SIVAL',
    client: 'Destination Angers / SIVAL',
    year: 2025,
    sector: 'Environnement',
    format: 'Série narrative promotionnelle',
    typology: 'Institution',
    location: 'Angers · Maine-et-Loire',
    tagline: 'Le SIVAL raconté à hauteur d’enfant devenu maraîcher innovant.',
    shortDescription: `Une saga musicale suit le petit-fils d’un maraîcher qui grandit avec le salon SIVAL et les conseils de Bruno Dupont. Chaque épisode montre l’évolution de l’agriculture française et l’ingéniosité des producteurs.`,
    longDescription: `En janvier 2025, Destination Angers nous confie une série de morceaux promotionnels pour le SIVAL, le Salon International des Techniques de Productions Végétales. Nous choisissons d’adopter le point de vue d’un enfant qui découvre l’exploitation de son grand-père et croise un collègue familier : Bruno Dupont, figure du salon.\n\nEn suivant cet enfant jusqu’à l’âge adulte, nous racontons l’évolution du SIVAL, l’arrivée des nouvelles technologies et la façon dont elles transforment son propre métier. Le récit reste ancré dans le réel, au plus près du quotidien d’un maraîcher, pour rendre hommage à celles et ceux qui travaillent la terre.`,
    roles: ['collectage', 'écriture', 'composition', 'interprétation'],
    partners: ['Équipes Destination Angers'],
    themes: ['agriculture', 'innovation', 'transmission', 'salon professionnel'],
    devices: ['suite de morceaux narratifs', 'voix & arrangements orchestraux'],
    status: 'delivered',
    isFeatured: true,
    order: 1,
  },
  {
    slug: 'la-force-de-la-douceur',
    title: 'Département de Maine-et-Loire — La force de la douceur',
    client: 'Département de Maine-et-Loire',
    year: 2024,
    sector: 'Institutionnel',
    format: 'Hymne officiel',
    typology: 'Institution',
    location: 'Anjou · Pays de la Loire',
    tagline: 'Un hymne qui dévoile la puissance tranquille et la créativité de l’Anjou.',
    shortDescription: `Commandé pour lancer la nouvelle marque du département, l’hymne exalte la diversité angevine. Deux clips — longue et courte durée — permettent une diffusion sur scène, en cinéma et sur les réseaux.`,
    longDescription: `En novembre 2024, le département du Maine-et-Loire nous confie la création de l’hymne « La force de la douceur ». En collaboration avec les compositeurs de musique de film Mathieu Coupat et Camille Després, ainsi que l’agence vidéo Kryzalid Films, nous produisons deux versions : une longue pour les Assises des départements de France et une courte pour les cinémas, la télévision et les réseaux sociaux.\n\nL’objectif : révéler toute la force contenue dans la douceur angevine, souligner sa diversité, son originalité et sa créativité. L’hymne combine écriture, composition et interprétation pour offrir une identité sonore immédiatement reconnaissable.`,
    roles: ['direction artistique', 'écriture', 'composition', 'interprétation'],
    partners: ['Mathieu Coupat', 'Camille Després', 'Kryzalid Films'],
    themes: ['identité territoriale', 'marque', 'émotion collective'],
    devices: ['hymne officiel', 'clips vidéo'],
    status: 'delivered',
    isFeatured: true,
    order: 2,
  },
  {
    slug: 'atelier-lacour-foret',
    title: 'Atelier Lacour — 25 ans & transmission',
    client: 'Atelier Lacour',
    year: 2024,
    sector: 'Artisanat',
    format: 'Suite de morceaux',
    typology: 'Entreprise',
    location: 'Pays de la Loire',
    tagline: 'Une métaphore forestière pour raconter la vie d’une entreprise familiale.',
    shortDescription: `Pour célébrer ses 25 ans et la passation de présidence, l’Atelier Lacour souhaitait que l’entreprise elle-même prenne la parole. Nous avons écrit une suite de morceaux où la croissance d’une forêt incarne l’histoire collective de l’équipe.`,
    longDescription: `En juillet 2024, Alain Lacour nous demande de créer un récit musical pour célébrer les 25 ans de son entreprise et accompagner la transmission à ses reprenants. Plutôt que de raconter la carrière d’un dirigeant, nous personnifions l’atelier : c’est l’entreprise qui parle, qui se souvient, qui transmet.\n\nLa métaphore filée de la forêt — un arbre qui grandit, rejoint par d’autres, affrontant les tempêtes — permet d’exprimer la cohésion, l’entraide et la robustesse du collectif. Le spectacle invite les collaborateurs à se reconnaître dans une histoire sensible et fédératrice.`,
    roles: ['collectage', 'écriture', 'composition', 'mise en voix'],
    themes: ['transmission', 'entreprise familiale', 'métaphore'],
    devices: ['suite de morceaux', 'performance live'],
    status: 'delivered',
    order: 3,
  },
  {
    slug: 'jardins-de-cocagne',
    title: 'Jardins de Cocagne — 25 ans de résilience',
    client: 'Réseau Jardins de Cocagne',
    year: 2024,
    sector: 'Vie associative',
    format: 'Triptyque musical',
    typology: 'Association',
    location: 'France',
    tagline: 'Trois trajectoires de vie qui convergent vers un même jardin solidaire.',
    shortDescription: `Pour les 25 ans du réseau, nous avons collecté la parole de Malya, Caroline et Ahmed. Trois récits musicaux racontent leurs chemins de traverse, leur courage et la force du collectif Cocagne.`,
    longDescription: `En juin 2024, l’association Jardins de Cocagne nous commande une série de morceaux pour célébrer un quart de siècle d’engagement. Leur souhait : rendre hommage à la résilience des jardiniers et jardinières qui construisent chaque jour ce réseau d’insertion.\n\nNous sommes allés à leur rencontre, avons enregistré leurs histoires et composé trois portraits croisés. Chaque morceau restitue la dignité, les doutes et les victoires de ces parcours atypiques. Les récits se rejoignent dans un même point : le jardin comme lieu de reconstruction et de solidarité.`,
    roles: ['collectage', 'écriture', 'composition', 'interprétation'],
    themes: ['résilience', 'insertion', 'agriculture solidaire'],
    devices: ['suite de morceaux', 'témoignages sonores'],
    status: 'delivered',
    order: 4,
  },
  {
    slug: 'etat-de-nature',
    title: 'État de Nature — PNR Loire-Anjou-Touraine',
    client: 'PNR Loire-Anjou-Touraine',
    coClients: ['PNR Médoc'],
    year: 2023,
    period: '2023 →',
    sector: 'Environnement',
    format: 'Spectacle immersif violon/voix',
    typology: 'Institution',
    location: 'Pays de la Loire & Médoc',
    tagline: 'Une société de zones humides qui se révèle en quinze tableaux musicaux.',
    shortDescription: `Spectacle itinérant joué en pleine nature pour sensibiliser aux zones humides. La Rainette, le Héron ou les libellules deviennent les citoyens d’une république aquatique à protéger.`,
    longDescription: `En avril 2023, le Parc naturel régional Loire-Anjou-Touraine souhaite sensibiliser le public à la fragilité des zones humides. Nous imaginons « État de Nature », un spectacle violon/voix joué directement au cœur des marais.\n\nLa Rainette, le Héron, les poissons-chats, les castors ou les libellules y forment une société bien organisée. Quinze tableaux dévoilent leurs voix, leurs enjeux et les services écosystémiques qu’ils rendent. Depuis sa création, la pièce a été jouée plus d’une trentaine de fois en Pays de la Loire. En février 2024, une version adaptée voit le jour pour le Parc naturel régional du Médoc.`,
    roles: ['écriture', 'composition', 'interprétation', 'médiation'],
    themes: ['zones humides', 'écologie', 'résilience territoriale'],
    devices: ['spectacle immersif', 'violon & voix'],
    status: 'delivered',
    playsCount: 30,
    isFeatured: true,
    order: 5,
  },
  {
    slug: 'capeb-artisans',
    title: 'CAPEB Maine-et-Loire — Artisans du bâtiment',
    client: 'CAPEB Maine-et-Loire',
    year: 2023,
    sector: 'BTP',
    format: 'Récit musical',
    typology: 'Organisation professionnelle',
    location: 'Maine-et-Loire',
    tagline: 'Guillaume, menuisier passionné, raconte son métier sans filtre.',
    shortDescription: `Carte blanche pour rendre hommage aux artisans du bâtiment. Après une immersion de deux jours sur le terrain, nous signons un morceau fidèle au quotidien des compagnons qui restaurent le patrimoine.`,
    longDescription: `En novembre 2023, la CAPEB Maine-et-Loire nous invite à raconter ce que signifie être artisan du bâtiment aujourd’hui. Nous suivons Guillaume, menuisier spécialisé dans la restauration patrimoniale, depuis la création de son atelier jusqu’à son adhésion à la CAPEB.\n\nLe récit, nourri d’entretiens et d’observations en atelier, restitue l’exigence, la fierté et la solidarité d’une filière. La musique souligne la noblesse des gestes et le lien entre artisanat et transmission.`,
    roles: ['immersion terrain', 'écriture', 'composition', 'interprétation'],
    themes: ['artisanat', 'patrimoine bâti', 'transmission'],
    devices: ['morceau narratif', 'collectage sonore'],
    status: 'delivered',
    order: 6,
  },
  {
    slug: 'clisson-deambulation',
    title: 'Clisson — Déambulation chevaleresque',
    client: 'Ville de Clisson',
    year: 2023,
    sector: 'Patrimoine',
    format: 'Spectacle déambulatoire',
    typology: 'Collectivité',
    location: 'Clisson · Loire-Atlantique',
    tagline: 'François d’Avaugour guide les visiteurs dans la Clisson du XVe siècle.',
    shortDescription: `Une visite musicale qui explore la période 1486-1487, lorsque Clisson passe de l’influence bretonne à française. L’esprit des romans de chevalerie rend l’histoire accessible et joyeuse.`,
    longDescription: `En juin 2023, la commune de Clisson souhaite une déambulation poétique dans son centre-ville. Après un collectage mené avec l’association Clisson Histoire et Patrimoine, nous concentrons le récit sur la période rarement évoquée de 1486-1487, quand la ville bascule de l’influence bretonne à française.\n\nGuidés par François Ier d’Avaugour, fils naturel du duc de Bretagne, les spectateurs découvrent une histoire médiévale pleine d’humour. Le spectacle joue avec les codes du roman de chevalerie pour offrir une expérience adaptée à tous les publics.`,
    roles: ['recherche historique', 'écriture', 'composition', 'interprétation'],
    themes: ['histoire', 'chevalerie', 'patrimoine'],
    devices: ['spectacle déambulatoire', 'violon & voix'],
    status: 'delivered',
    order: 7,
  },
  {
    slug: 'brissac-loire-aubance',
    title: 'Brissac Loire Aubance — Don Quichotte en Anjou',
    client: 'Brissac Loire Aubance',
    year: 2023,
    sector: 'Patrimoine',
    format: 'Déambulation narrative',
    typology: 'Collectivité',
    location: 'Brissac · Anjou',
    tagline: 'La suite de Don Quichotte se joue au milieu des vignes brissacoises.',
    shortDescription: `Pour les Journées européennes du patrimoine, nous imaginons la venue de Don Quichotte en Anjou. Entre moulins, vignobles et humour, le récit fait dialoguer littérature espagnole et mémoire locale.`,
    longDescription: `En septembre 2023, la commune de Brissac Loire Aubance nous confie un spectacle déambulatoire autour de son vignoble. Nous avons carte blanche : nous décidons de poursuivre l’histoire de Don Quichotte. Le chevalier arrive en Anjou pour investir le vignoble local, entraînant Sancho Panza dans une aventure burlesque.\n\nLa déambulation mêle les passages emblématiques du roman — moulins, moutons, illusions — aux détails de l’histoire régionale. Le format violon/voix permet une mise en scène légère qui suit le public dans le vignoble.`,
    roles: ['écriture', 'composition', 'interprétation'],
    themes: ['vignoble', 'littérature', 'patrimoine'],
    devices: ['déambulation musicale', 'violon & voix'],
    status: 'delivered',
    order: 8,
  },
  {
    slug: 'agglobus-saumur',
    title: 'Agglo’bus — Bien voyager ensemble',
    client: 'Agglomération Saumur Val de Loire',
    year: 2023,
    sector: 'Transport',
    format: 'Texte vidéo narratif',
    typology: 'Collectivité',
    location: 'Saumur · Val de Loire',
    tagline: 'Deux collégiens transforment le bus en lieu de lien social.',
    shortDescription: `Un texte de prévention qui montre le bus comme un espace vivant, sécurisant et convivial. Réalisé avec l’agence Terre de Pixels pour guider les usagers du réseau Agglo’bus.`,
    longDescription: `En juin 2023, la communauté d’agglomération Saumur Val de Loire nous commande un texte de prévention pour le réseau Agglo’bus. Avec l’agence Terre de Pixels à la réalisation vidéo, nous racontons l’histoire de deux collégiens un matin d’hiver.\n\nLe bus devient à la fois un moyen de transport quotidien et un symbole de rencontres. Chaque trajet rappelle les règles de sécurité tout en valorisant le lien social tissé dans les transports publics.`,
    roles: ['écriture', 'voix off', 'conseil éditorial'],
    partners: ['Terre de Pixels'],
    themes: ['mobilité douce', 'jeunesse', 'prévention'],
    devices: ['texte vidéo', 'voix off'],
    status: 'delivered',
    order: 9,
  },
  {
    slug: 'doue-en-anjou-voeux',
    title: 'Doué-en-Anjou — Vœux du Maire',
    client: 'Ville de Doué-en-Anjou',
    year: 2022,
    sector: 'Patrimoine',
    format: 'Texte performé',
    typology: 'Collectivité',
    location: 'Doué-en-Anjou',
    tagline: 'Quand le temps se suspend entre patrimoine et scène culturelle.',
    shortDescription: `Texte écrit pour les vœux du Maire, réalisé avec Terre de Pixels. Nous explorons l’idée d’un temps qui se fige pour révéler la force culturelle et patrimoniale de la ville.`,
    longDescription: `En janvier 2022, Doué-en-Anjou nous sollicite pour écrire un texte destiné aux vœux du Maire. Aux côtés de l’agence locale Terre de Pixels, nous cherchons comment faire dialoguer patrimoine et culture contemporaine.\n\nNous choisissons le thème du temps suspendu : au théâtre comme devant un monument, la perception s’étire, les souvenirs se superposent. Le texte invite habitants et partenaires à contempler la ville, à comprendre comment passé et présent coexistent pour créer une harmonie singulière.`,
    roles: ['écriture', 'voix off'],
    partners: ['Terre de Pixels'],
    themes: ['patrimoine', 'culture', 'temps'],
    devices: ['texte vidéo', 'voix off'],
    status: 'delivered',
    order: 10,
  },
  {
    slug: 'theatre-jeune-plume',
    title: 'Théâtre de la Jeune Plume — Doubles créations',
    client: 'Théâtre de la Jeune Plume',
    year: 2023,
    period: '2021–2023',
    sector: 'Spectacle vivant',
    format: 'Bandes-son scéniques',
    typology: 'Compagnie artistique',
    location: 'Pays de la Loire',
    tagline: 'Deux spectacles pour lever le voile sur des sujets sensibles.',
    shortDescription: `« Dis-moi des mots d’amour » aborde les affections de longue durée, « Souffler sur les braises » parle de l’intimité des aînés. Recherche, collectage et création sonore accompagnent les danseurs sur scène.`,
    longDescription: `De novembre 2021 à mars 2023, nous collaborons avec le Théâtre de la Jeune Plume pour créer deux spectacles musicaux. « Dis-moi des mots d’amour » traite des affections de longue durée ; « Souffler sur les braises » évoque la vie intime des personnes âgées.\n\nPour chaque projet, nous réalisons une phase de recherche et de collectage auprès des publics concernés afin d’éviter tout cliché. Les bandes-son diffusées sur scène accompagnent les danseurs et ouvrent un espace de parole sensible et respectueux.`,
    roles: ['recherche', 'collectage', 'composition', 'design sonore'],
    themes: ['santé', 'intimité', 'tabous'],
    devices: ['bande-son scénique', 'création sonore immersive'],
    status: 'delivered',
    playsCount: 20,
    order: 11,
  },
  {
    slug: 'chemin-des-dames',
    title: 'Le chemin des dames',
    client: 'Autoproduction',
    year: 2026,
    sector: 'Spectacle vivant',
    format: 'Dîner-spectacle immersif',
    typology: 'Autoproduction',
    location: 'Angers - Paris',
    cover: '/assets/images/projects/chemin-des-dames-cover.jpg',
    tagline: 'Dîner-spectacle immersif historique en partenariat avec Les petits pères.',
    shortDescription: `Le chemin des dames est un concept de dîner-spectacle immersif historique. En partenariat avec Les petits pères.`,
    longDescription: `Le chemin des dames est le premier projet autoproduit d’en français s’il vous plaît. Il est en cours de construction. Les premières représentations sont prévues pour l’année 2026.\n\nLe concept : un dîner-spectacle historique immersif racontant l’histoire de 4 soldats le 16 avril 1917 au matin. Chaque acte nous plonge dans le passé d’un personnage. Les plats répondent à l’histoire. Toute la musique est jouée en live.\n\nLe chemin des dames est réellement à la croisée entre le spectacle et le dîner gastronomique. Une dizaine de plats, 5 actes, le service, la vaisselle, le décor, tout est inclus dans l’histoire.`,
    roles: ['direction artistique', 'écriture', 'composition', 'interprétation'],
    partners: ['Les petits pères'],
    themes: ['première guerre mondiale', 'patrimoine', 'gastronomie', 'spectacle vivant'],
    devices: ['dîner-spectacle immersif', 'musique live'],
    status: 'in_production',
    order: 12,
  },
];

export const projectsBySlug = projectsCollection.reduce((acc, project) => {
  acc[project.slug] = project;
  return acc;
}, {});
